apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: {{ include "orderfulfilment-engine.name" . }}
    helm.sh/chart: {{ include "orderfulfilment-engine.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ .Release.Name }}
    serive: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http-{{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      nodePort: {{ .Values.service.nodePort}}
  selector:
    app.kubernetes.io/name: {{ include "orderfulfilment-engine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
