# Default values for customer-journey-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: azeastusitacr.azurecr.io/orderfulfilment
  tag: latest
  pullPolicy: Always
  
service:
  name: orderfulfilment
  type: ClusterIP
  port: 8080
  targetPort: 8080
  containerPort: 8080 

# Service specific env variables
envVariables:
  BUILD: 2


resources:
   limits:
     cpu: 500m
     memory: 750Mi
   requests:
     cpu: 200m
     memory: 285Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

ingressGateway:
  name: appsdev-gateway-https
  host: "webapi-dev.ptc.com"
  matchPrefix: "/orderfulfilment-engine/"
  rewrite: "/"  

# The overall timeout for requests to this service
# Optional
overallTimeout: 10s

# Client retry settings (use Istio syntax)
# Optional
retries:
  attempts: 3
  perTryTimeout: 2s

# Circuit breaker settings (use Istio syntax)
# Optional
outlierDetection: 
  consecutive5xxErrors: 5

podidbinding: azureaccess  

# healthCheck:
#   liveness: /actuator/health
#   readiness: /actuator/health
#   port: 9003
#   initialDelaySeconds: 30

serviceAccountName: 

tolerations: []

nodeSelector: 
  approle: "app"

affinity: {}
